// src/constants/products.ts
import { Product } from '../types';

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Sony WH-1000XM5 Headphones',
    price: 24999,
    originalPrice: 34990,
    discount: 28,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    rating: 4.8,
    reviews: 2341,
    inStock: true,
    description: 'Industry-leading noise cancellation with 30hr battery life',
    tags: ['headphones', 'wireless', 'noise cancellation', 'sony', 'audio'],
  },
  {
    id: 'p2',
    name: 'Apple AirPods Pro (2nd Gen)',
    price: 19999,
    originalPrice: 26900,
    discount: 26,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400',
    rating: 4.7,
    reviews: 5820,
    inStock: true,
    description: 'Active noise cancellation, spatial audio, 6hr battery',
    tags: ['airpods', 'apple', 'earbuds', 'wireless', 'audio'],
  },
  // {
  //   id: 'p3',
  //   name: 'Samsung 65" 4K Smart TV',
  //   price: 54999,
  //   originalPrice: 79990,
  //   discount: 31,
  //   category: 'Electronics',
  //   image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400',
  //   rating: 4.6,
  //   reviews: 1203,
  //   inStock: true,
  //   description: 'Crystal UHD 4K, Tizen OS, Dolby Atmos',
  //   tags: ['tv', 'samsung', '4k', 'smart tv', 'television'],
  // },
  {
    id: 'p4',
    name: 'Nike Air Max 270',
    price: 7495,
    originalPrice: 10995,
    discount: 32,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    rating: 4.5,
    reviews: 3102,
    inStock: true,
    description: 'Max cushioning for all-day comfort, breathable mesh upper',
    tags: ['nike', 'shoes', 'running', 'sports', 'footwear'],
  },
  {
    id: 'p5',
    name: 'Adidas Ultraboost 22',
    price: 8999,
    originalPrice: 14999,
    discount: 40,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400',
    rating: 4.7,
    reviews: 2890,
    inStock: true,
    description: 'Boost technology, Primeknit upper, perfect for running',
    tags: ['adidas', 'shoes', 'running', 'sports', 'ultraboost'],
  },
  {
    id: 'p6',
    name: 'Lakme 9to5 Foundation',
    price: 449,
    originalPrice: 649,
    discount: 31,
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400',
    rating: 4.3,
    reviews: 8721,
    inStock: true,
    description: 'Full coverage, 16hr wear, SPF 20, 15 shades',
    tags: ['lakme', 'foundation', 'makeup', 'beauty', 'face'],
  },
  {
    id: 'p7',
    name: 'Maybelline Fit Me Concealer',
    price: 299,
    originalPrice: 399,
    discount: 25,
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400',
    rating: 4.4,
    reviews: 6540,
    inStock: true,
    description: 'Natural finish, buildable coverage, 40 shades',
    tags: ['maybelline', 'concealer', 'makeup', 'beauty'],
  },
  {
    id: 'p8',
    name: 'Wildcraft 45L Backpack',
    price: 1799,
    originalPrice: 2999,
    discount: 40,
    category: 'Bags',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
    rating: 4.5,
    reviews: 4210,
    inStock: true,
    description: 'Water resistant, padded laptop sleeve, multiple compartments',
    tags: ['wildcraft', 'backpack', 'bags', 'travel', 'laptop bag'],
  },
  {
    id: 'p9',
    name: 'Fossil Gen 6 Smartwatch',
    price: 14999,
    originalPrice: 22995,
    discount: 35,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
    rating: 4.4,
    reviews: 1890,
    inStock: true,
    description: 'Wear OS, heart rate monitor, GPS, 24hr battery',
    tags: ['fossil', 'smartwatch', 'watch', 'wearable', 'android'],
  },
  {
    id: 'p10',
    name: 'Yoga Mat Premium 6mm',
    price: 999,
    originalPrice: 1799,
    discount: 44,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=400',
    rating: 4.6,
    reviews: 3201,
    inStock: true,
    description: 'Anti-slip, eco-friendly TPE material, carry strap included',
    tags: ['yoga mat', 'fitness', 'exercise', 'sports', 'yoga'],
  },
  {
    id: 'p11',
    name: 'L\'Oreal Revitalift Serum',
    price: 799,
    originalPrice: 1299,
    discount: 38,
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400',
    rating: 4.5,
    reviews: 5621,
    inStock: true,
    description: '1.5% pure hyaluronic acid, plumping & anti-aging',
    tags: ['loreal', 'serum', 'skincare', 'beauty', 'anti-aging'],
  },
  {
    id: 'p12',
    name: 'Herschel Little America Backpack',
    price: 5499,
    originalPrice: 7999,
    discount: 31,
    category: 'Bags',
    image: 'https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=400',
    rating: 4.7,
    reviews: 2340,
    inStock: true,
    description: 'Classic design, 25L capacity, laptop sleeve, dual top handles',
    tags: ['herschel', 'backpack', 'bags', 'laptop bag', 'travel'],
  },
  {
    id: 'p13',
    name: 'boAt Rockerz 450 Headphones',
    price: 1299,
    originalPrice: 3990,
    discount: 67,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400',
    rating: 4.2,
    reviews: 12430,
    inStock: true,
    description: 'Bluetooth 5.0, 15hr battery, built-in mic, foldable design',
    tags: ['boat', 'headphones', 'wireless', 'bluetooth', 'audio'],
  },
  {
    id: 'p14',
    name: 'Fastrack Ruffles Handbag',
    price: 2299,
    originalPrice: 3499,
    discount: 34,
    category: 'Bags',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
    rating: 4.3,
    reviews: 1890,
    inStock: true,
    description: 'Vegan leather, structured design, magnetic snap closure',
    tags: ['fastrack', 'handbag', 'bags', 'women', 'fashion'],
  },
  {
    id: 'p15',
    name: 'Puma Sports Bottle 750ml',
    price: 499,
    originalPrice: 999,
    discount: 50,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400',
    rating: 4.4,
    reviews: 7650,
    inStock: true,
    description: 'BPA free, leak-proof cap, stainless steel, keeps cold 24hr',
    tags: ['puma', 'water bottle', 'sports', 'fitness', 'gym'],
  },
  {
    id: 'p16',
    name: 'Nykaa Lip Matte Lipstick',
    price: 349,
    originalPrice: 499,
    discount: 30,
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1586495777744-4e6232bf2177?w=400',
    rating: 4.4,
    reviews: 9210,
    inStock: true,
    description: 'Long lasting matte finish, 30+ shades, moisturizing formula',
    tags: ['nykaa', 'lipstick', 'makeup', 'beauty', 'matte'],
  },
];

export const CATEGORIES = ['Electronics', 'Sports', 'Beauty', 'Bags'];
export const BEST_DEAL_IDS = ['p13', 'p10', 'p15', 'p6'];

export const getProductById = (id: string): Product | undefined =>
  PRODUCTS.find(p => p.id === id);

export const getProductsByCategory = (category: string): Product[] =>
  PRODUCTS.filter(p => p.category === category);

export const getProductsByIds = (ids: string[]): Product[] =>
  ids.map(id => getProductById(id)).filter(Boolean) as Product[];
